# Giriş

Bu bölümde göreceğimiz nokta çarpım, veri bilimi algoritmalarını açıklayan her denklemde kullanılır, bu sebeple oldukça önemlidir ve bu işlemin bazı özelliklerini de bilmek gerekir. En son olarak, matrisler ve lineer denklem sistemleri arasındaki bağlantı hakkında biraz fikir edineceğiz.


# 2.2 Matris ve Vektörlerin Çarpımı

Matrisleri çarpmanın standart yolu, birinin her bir elemanını diğerinin her bir elemanı ile çarpmak değildir (bu eleman bazında çarpımdır). Matris çarpımında satırlar ve sütunlar arasındaki çarpımların toplamını hesaplamak gerekir. **nokta çarpım** olarak da adlandırılan matris çarpımı aşağıdaki gibi hesaplanır:

<img src="https://drive.google.com/uc?id=1opgFQvPMw7XYGKeNDQ6ajMbhNdEiMU-n" width="400" alt="An example of how to calculate the dot product between a matrix and a vector" title="The dot product between a matrix and a vector">

<em>Bir matris ve bir vektörün nokta çarpımı</em>

Birinci matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olmalıdır. Bu nedenle, birinci matrisin boyutları veya şekli ($m \times n$) ise, ikinci matrisin şekilli olması gerekir ($n \times x$). Ortaya çıkan matris ($m \times x$) şeklinde olacaktır.

### Örnek 1.

Başlangıç olarak, bir matris ve bir vektörün çarpımını görelim.


$${A} \times {b} = {C}$$

$
{A}=
\begin{bmatrix}
    1 & 2\\\\
    3 & 4\\\\
    5 & 6
\end{bmatrix}
$ ile ${b}=\begin{bmatrix}
    2\\\\
    4
\end{bmatrix}$. Formülün aşağıdaki gibi olduğunu görebiliriz:

$$
\begin{align*}
&\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1}
\end{bmatrix}=\\\\
&\begin{bmatrix}
    A_{1,1}B_{1,1} + A_{1,2}B_{2,1} \\\\
    A_{2,1}B_{1,1} + A_{2,2}B_{2,1} \\\\
    A_{3,1}B_{1,1} + A_{3,2}B_{2,1}
\end{bmatrix}
\end{align*}
$$

Böylece sahip olacağımız şey :

$$
\begin{align*}
&\begin{bmatrix}
    1 & 2 \\\\
    3 & 4 \\\\
    5 & 6
\end{bmatrix}\times
\begin{bmatrix}
    2 \\\\
    4
\end{bmatrix}=\\\\
&\begin{bmatrix}
    1 \times 2 + 2 \times 4 \\\\
    3 \times 2 + 4 \times 4 \\\\
    5 \times 2 + 6 \times 4
\end{bmatrix}=
\begin{bmatrix}
    10 \\\\
    22 \\\\
    34
\end{bmatrix}
\end{align*}
$$

Neler olduğunu görmek için matrisin boyutlarını kontrol etmek iyi bir alışkanlıktır. Bu örnekte ${A}$ şeklinin ($3 \times 2$) ve ${b}$ şeklinin ($2 \times 1$) olduğunu görebiliriz. Yani ${C}$'ın boyutları ($3 \times 1$).

### Numpy ile Gerçekleyelim

`dot()` Numpy fonksiyonu matris çarpımı (nokta çarpımı) için kullanılabilir. Son örneği yeniden oluşturmaya çalışalım:

In [ ]:
import numpy as np

In [ ]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors

#np.set_printoptions(suppress=True)

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [ ]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

Numpy dizilerinin "dot()" yöntemini kullanması ile eşdeğerdir:

In [ ]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

### Örnek 2.

2 Matrisin Çarpımı

$${A} \times {B} = {C}$$

ile:

$${A}=\begin{bmatrix}
    1 & 2 & 3 \\\\
    4 & 5 & 6 \\\\
    7 & 8 & 9 \\\\
    10 & 11 & 12
\end{bmatrix}
$$

ve:

$${B}=\begin{bmatrix}
    2 & 7 \\\\
    1 & 2 \\\\
    3 & 6
\end{bmatrix}
$$

Böylece:

$$
\begin{align*}
&\begin{bmatrix}
    1 & 2 & 3 \\\\
    4 & 5 & 6 \\\\
    7 & 8 & 9 \\\\
    10 & 11 & 12
\end{bmatrix}\times
\begin{bmatrix}
    2 & 7 \\\\
    1 & 2 \\\\
    3 & 6
\end{bmatrix}=\\\\
&\begin{bmatrix}
    2 \times 1 + 1 \times 2 + 3 \times 3 & 7 \times 1 + 2 \times 2 + 6 \times 3 \\\\
    2 \times 4 + 1 \times 5 + 3 \times 6 & 7 \times 4 + 2 \times 5 + 6 \times 6 \\\\
    2 \times 7 + 1 \times 8 + 3 \times 9 & 7 \times 7 + 2 \times 8 + 6 \times 9 \\\\
    2 \times 10 + 1 \times 11 + 3 \times 12 & 7 \times 10 + 2 \times 11 + 6 \times 12 \\\\
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    13 & 29 \\\\
    31 & 74 \\\\
    49 & 119 \\\\
    67 & 164
\end{bmatrix}
\end{align*}
$$

Sonucu Numpy ile kontrol edelim:

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [ ]:
C = A.dot(B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

İşe yarıyor!

# Nokta çarpımın formüle edilmesi

$$
C_{i,j} = A_{i,k}B_{k,j} = \sum_{k}A_{i,k}B_{k,j}
$$

Nokta çarpımı hakkında daha fazla örnek bulabilirsiniz [bknz](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

# Nokta çarpımın özellikleri

Şimdi matris çarpımının bazı ilginç özelliklerini göreceğiz. İleyen kısımlarda bu özellikler faydalı olacaktır. Her özellik için basit örnekler kullanmak, Numpy işlevlerine alışırken onları kontrol etmenin bir yolunu sağlayacaktır.


## Matris çarpımının dağılma özelliği vardır

$${A}({B}+{C}) = {AB}+{AC}$$

### Örnek 3.

$$
{A}=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}, 
{B}=\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}, 
{C}=\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}
$$


$$
\begin{align*}
{A}({B}+{C})&=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\left(\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\right)=
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    9 \\\\
    5
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    2 \times 9 + 3 \times 5 \\\\
    1 \times 9 + 4 \times 5 \\\\
    7 \times 9 + 6 \times 5
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
\end{align*}
$$

eşittir

$$
\begin{align*}
{A}{B}+{A}{C} &= \begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    2 \times 5 + 3 \times 2 \\\\
    1 \times 5 + 4 \times 2 \\\\
    7 \times 5 + 6 \times 2
\end{bmatrix}+
\begin{bmatrix}
    2 \times 4 + 3 \times 3 \\\\
    1 \times 4 + 4 \times 3 \\\\
    7 \times 4 + 6 \times 3
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    16 \\\\
    13 \\\\
    47
\end{bmatrix}+
\begin{bmatrix}
    17 \\\\
    16 \\\\
    46
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
\end{align*}
$$

In [ ]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [ ]:
B = np.array([[5], [2]])
B

array([[5],
       [2]])

In [ ]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

${A}({B}+{C})$:

In [ ]:
D = A.dot(B+C)
D

array([[33],
       [29],
       [93]])

eşittir ${AB}+{AC}$:

In [ ]:
D = A.dot(B) + A.dot(C)
D

array([[33],
       [29],
       [93]])

## Matris çarpımı ilişkiseldir

$${A}({BC}) = ({AB}){C}$$


In [ ]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [ ]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

${A}({BC})$:


In [ ]:
D = A.dot(B.dot(C))
D

array([[100],
       [ 85],
       [287]])

eşittir $({AB}){C}$:

In [ ]:
D = (A.dot(B)).dot(C)
D

array([[100],
       [ 85],
       [287]])

## Matris çarpımı değişmeli değildir

$${AB} \neq {BA}$$

In [ ]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [ ]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

${AB}$:

In [ ]:
AB = np.dot(A, B)
AB

array([[16, 12],
       [40, 28]])

${BA}$'a eşit değildir:

In [ ]:
BA = np.dot(B, A)
BA

array([[28, 30],
       [16, 16]])

## Ancak vektör çarpması değişmelidir.

$${x^{ \text{T}}y} = {y^{\text{T}}x} $$

In [ ]:
x = np.array([[2], [6]])
x

array([[2],
       [6]])

In [ ]:
y = np.array([[5], [2]])
y

array([[5],
       [2]])

${x^\text{T}y}$:

In [ ]:
x_ty = x.T.dot(y)
x_ty

array([[22]])

eşittir ${y^\text{T}x}$:

In [ ]:
y_tx = y.T.dot(x)
y_tx

array([[22]])

## Matris çarpımının sadeleştirilmesi

$$({AB})^{\text{T}} = {B}^\text{T}{A}^\text{T}$$

In [ ]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [ ]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$({AB})^{\text{T}}$:

In [ ]:
AB_t = A.dot(B).T
AB_t

array([[16, 13, 47],
       [12, 11, 33]])

eşittir ${B}^\text{T}{A}^\text{T}$:

In [ ]:
B_tA = B.T.dot(A.T)
B_tA

array([[16, 13, 47],
       [12, 11, 33]])

# Lineer denklemler sistemi

Bir denklem sistemi, çoklu denklemler kümesidir (en az 1 olmak üzere). Örneğin şunlara sahip olabiliriz:

$$
\begin{cases}
y = 2x + 1 \\\\
y = \frac{7}{2}x +3
\end{cases}
$$

Bir denklem sistemi, denklem sayısı ve bilinmeyen sayısı ile tanımlanır. Yukarıdaki örneğimizde, sistemin 2 denklemi ve 2 bilinmeyeni vardır ($x$ ve $y$). Buna ek olarak, her denklem lineer olduğu için buna **lineer** denklemler sistemi diyoruz. Bunu 2 boyutta görmek kolaydır: denklem başına bir düz çizgimiz olacak ve boyutlar bilinmeyenlerdir. İşte ilki:

<img src="https://drive.google.com/uc?id=1b62hanvVQ1HYmnI1IlgVDgEtwIW4pGs9"  width="300" alt="Representation of a line from an equation" title="Plot of a linear equation">

<em>Doğrusal bir denklemin gösterimi</em>

$$
<span class='pquote'>
    Denklem sistemimizde, bilinmeyenler boyutlardır ve denklemlerin sayısı doğruların (2B'de) veya $n$ boyutlu düzlemlerin sayısıdır.
</span>


## Sistemi tanımlamak için matrisleri kullanma

Matrisler, ${Ax}={b}$ biçimindeki bir lineer denklem sistemini tanımlamak için kullanılabilir. İşte böyle bir sistem:

$$
A_{1,1}x_1 + A_{1,2}x_2 + A_{1,n}x_n = b_1 \\\\
A_{2,1}x_1 + A_{2,2}x_2 + A_{2,n}x_n = b_2 \\\\
\cdots \\\\
A_{m,1}x_1 + A_{m,2}x_2 + A_{m,n}x_n = b_n
$$

Bilinmeyenler (sistemi çözmek için bulmak istediğimiz), önceki $x$ ve $y$ değişkenlerine karşılık gelen $x_1$ ve $x_2$ değişkenleridir. Son örnektekiyle tamamen aynı formdadır, ancak tüm değişkenler aynı taraftadır. $y = 2x + 1$, $x_1$'a karşılık gelen $x$ ve $x_2$'a karşılık gelen $y$ ile $-2x + y = 1$ olur. $n$ bilinmeyenlerimiz ve $m$ denklemlerimiz olacak.

Değişkenler, geleneksel olarak $x_1, x_2, \cdots, x_n$ olarak adlandırılır çünkü bunun ${x}$ vektöründe özetlenebileceğini göreceğiz.

### Sol taraftaki

Sol taraftaki terim, her değişken ($n$ sütun) ve her denklem ($m$ satır) için ağırlıkları içeren bir ${A}$ matrisinin ürünü olarak düşünülebilir:

$$
{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

$n$ bilinmeyenlerini içeren bir ${x}$ vektörüyle

$$
{x}=
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$$

${A}$ ve ${x}$'ın nokta çarpımı bir dizi denklem verir. İşte basit bir örnek:

<img src="https://drive.google.com/uc?id=1zcvM-_b0Yp1GBm1B3ZHd4u4D9knYvQLx" width="400" alt="Matrix form of a system of linear equation" title="Matrix form of a system of linear equation">

<em>Lineer denklem sisteminin matris formu</em>

İki bilinmeyenli iki denklemimiz var. Böylece ${A}$ satır sayısı denklem sayısını verir ve sütun sayısı bilinmeyenlerin sayısını verir.

### İki taraf da

Denklem sistemi şu şekilde yazılabilir:

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
\times
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
=
\begin{bmatrix}
    b_1 \\\\
    b_2 \\\\
    \cdots \\\\
    b_m
\end{bmatrix}
$$

Ya da sadece:

$${Ax}={b}$$

### Örnek 4.

$y=ax+b$ lineer denkleminin ortak formunu matris formuna dönüştürmeye çalışacağız. Önceki gösterimi korumak istiyorsak, bunun yerine:

$$x_2=ax_1+b$$

$x_1$ ve $x_2$ değişkenlerini ${x}$ vektörüyle karıştırmayın. Bu vektör aslında denklemlerimizin tüm değişkenlerini içerir. İşte bizde:

$$
{x} =
\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix}
$$

Bu örnekte aşağıdaki denklemi kullanacağız:

$$
\begin{align*}
&x_2=2x_1+1\\\\
\Leftrightarrow& 2x_1-x_2=-1
\end{align*}
$$

${A}$ ve ${x}$'ı çarptığımızda bu sistemi elde etmek için, her değişkenin ağırlıklarını içeren bir matris olmak üzere ${A}$'a ihtiyacımız var. $x_1$'ın ağırlığı $2$'dır ve $x_2$'ın ağırlıkları $-1$'dır:

$$
{A}=
\begin{bmatrix}
    2 & -1
\end{bmatrix}
$$

Böylece :

$$
\begin{bmatrix}
    2 & -1
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix}
=
\begin{bmatrix}
2x_1-1x_2
\end{bmatrix}
$$

Elimizdeki denklemi tamamlamak için

$$
{b}=
\begin{bmatrix}
    -1
\end{bmatrix}
$$



$$
\begin{bmatrix}
    2 & -1
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix}
=
\begin{bmatrix}
    -1
\end{bmatrix}
$$

Bu denklem sistemi bu nedenle çok basittir ve yalnızca 1 denklem (${A}$'da 1 satır vardır) ve 2 değişken (${A}$'da 2 sütun vardır) içerir.

Özetlemek gerekirse, ${A}$, bu değişkenleri çarpan skalerleri içeren $m\times n$ boyutlarının matrisi olacaktır (burada $x_1$ 2 ile ve $x_2$ -1 ile çarpılır). ${x}$ vektörü, $x_1$ ve $x_2$ değişkenlerini içerir. Ve sağ taraftaki terim ${b}$ sabitidir:

$$
{A}=
\begin{bmatrix}
    2 & -1
\end{bmatrix}
$$

$$
{x}=
\begin{bmatrix}
    x_1\\\\
    x_2
\end{bmatrix}
$$

$$
{b}=
\begin{bmatrix}
    -1
\end{bmatrix}
$$

bu sistemi böyle yazabiliriz :

$$
{Ax}={b}
$$

[Bir sonraki bölümün](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.3-Identity-and-Inverse-Matrices/) sonunda göreceğiz lineer denklem setleri yazmak çok faydalı olabilir. Aslında denklemleri çözmek için bir yol sağlar.

# Referanslar

- [Math is fun - Multiplying matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html)